apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: EKS-devops-cluster
  region: us-east-1
vpc:
  subnets:
    public:
      us-east-1d: { id: "subnet-84c5ebc9" }
      us-east-1b: { id: "subnet-a1bb25c7" }
nodeGroups:
  - name: ng-1
    instanceType: t2.small
    desiredCapacity: 2
    ssh: # use existing EC2 key
      publicKeyName: key-pair-264055 #devops
